### PR TITLE
Add Redux Keen to community-projects.md

### PR DESCRIPTION
**Pull request by arturmuller**
This is a small utility library that we have created for Redux apps. It allows you to send events to Keen based on your Redux actions, which is how almost every interaction is handled in Redux apps... Makes adding analytics to these kinds of apps easy to set up, manage, and maintain. See more [here](https://github.com/pavelvolek/redux-keen).

### CODE REVIEW

**Comment by tbarn** [comment]
:+1: Thanks for the contribution @arturmuller !

**Comment by arturmuller** [comment]
Thank _you_ for an awesome product!

**Comment by timfalls** [comment]
woot! @arturmuller wins the prize for first official PR for adding a new project to this repo! (outside of Keen employees)

Thanks a ton, Artur 🤓 We appreciate you!

**Comment by arturmuller** [comment]
Yay! :tada: Hope this is just the beginning of things we will build with Keen!

BTW, as a side note: when my friend @veronikasoltes was doing research for who to go with for our analytics, we have went through quite a few options but in the end what won us over was how friendly and approachable everything around Keen seemed.

Good job on you community team! :)

**Comment by timfalls** [comment]
@veronikasoltes @arturmuller -- that's incredible to hear, and I truly appreciate you sharing that testimonial with us. As you can imagine, feedback like this plays a big role in making our jobs (aka, lives!) enjoyable and rewarding. 

THANK **YOU**! And never hesitate to let us know what we can do even better to help make _your_ lives even more awesome 😺

**Comment by arturmuller** [comment]
😊

**Pull request merged**
